kind: Secret
apiVersion: v1
metadata:
  name: <DATACONNECTION_NAME>
  namespace: <PROJECT>
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: <DATACONNECTION_NAME>
stringData:
  AWS_ACCESS_KEY_ID: <ACCESS_KEY>
  AWS_DEFAULT_REGION: <REGION>
  AWS_S3_BUCKET: <BUCKET_NAME>
  AWS_S3_ENDPOINT: <HTTP_ENDPOINT>:<PORT>
  AWS_SECRET_ACCESS_KEY: <SECRET_KEY>
type: Opaque
